services:
  phantom-plugin:
    image: ghcr.io/curity/tyk-phantom-plugin:latest
    # If your gateway nodes are amd64 and you're on Apple Silicon locally:
    # platform: linux/amd64
    environment:
      PORT: 50051
      INTROSPECTION_URL: ${INTROSPECTION_URL}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    expose: ["50051"]
    pull_policy: always
    networks: [tyk]

  bundle-fetch:
    image: curlimages/curl:8.9.1
    volumes:
      - ./bundles:/work
    command:
      - sh
      - -lc
      - >
        set -e;
        mkdir -p /work;
        echo "Downloading latest phantom-bundle.zip...";
        curl -sSL -o /work/phantom-bundle.zip
        https://github.com/curity/tyk-phantom-token-plugin/releases/latest/download/phantom-bundle.zip;
        ls -lh /work/phantom-bundle.zip

  bundle-server:
    image: nginx:alpine
    depends_on:
      bundle-fetch:
        condition: service_completed_successfully
    volumes:
      - ./bundles:/usr/share/nginx/html:ro
    expose: ["80"]
    networks: [tyk]

networks:
  tyk:
    external: true
    name: tyk-self-managed-trial_tyk
