name: Build Bundle ZIP

on:
  push:
    branches: [ main, initial-code ]
  pull_request:
    branches: [ main, initial-code ]
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write
  packages: read         

env:
  BUNDLE_NAME: phantom-bundle.zip

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR       
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build signed bundle with tyk-cli
        run: |
          mkdir -p bundles
          docker run --rm \
            -v "$GITHUB_WORKSPACE/manifest:/work/manifest:ro" \
            -v "$GITHUB_WORKSPACE/bundles:/work/out" \
            ghcr.io/tyktechnologies/tyk-cli:latest \
            bundle build -y -p /work/manifest -o /work/out/${{ env.BUNDLE_NAME }}

      - name: Generate checksum
        run: |
          cd bundles
          sha256sum "${{ env.BUNDLE_NAME }}" | tee "${{ env.BUNDLE_NAME }}.sha256"

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUNDLE_NAME }}
          path: |
            bundles/${{ env.BUNDLE_NAME }}
            bundles/${{ env.BUNDLE_NAME }}.sha256
          retention-days: 14

      - name: Attach to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bundles/${{ env.BUNDLE_NAME }}
            bundles/${{ env.BUNDLE_NAME }}.sha256
