# .github/workflows/build-bundle.yml
name: Build Bundle ZIP

on:
  push:
    branches: [ main, initial-code ]
  pull_request:
    branches: [ main, initial-code ]
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write

env:
  BUNDLE_NAME: phantom-bundle.zip
  GATEWAY_TAG: v5.9.0   # pin to a known good

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build signed bundle with gateway image
        run: |
          mkdir -p bundles
          docker run --rm \
            --entrypoint /bin/sh \
            -v "$GITHUB_WORKSPACE/manifest:/work/manifest:ro" \
            -v "$GITHUB_WORKSPACE/bundles:/work/out" \
            tykio/tyk-gateway:v5.9.0 \
            -lc 'cd /work/manifest && /opt/tyk-gateway/tyk bundle build -y -o /work/out/phantom-bundle.zip'
          ls -lh bundles/phantom-bundle.zip

      - name: Generate checksum
        run: |
          cd bundles
          sha256sum "${{ env.BUNDLE_NAME }}" | tee "${{ env.BUNDLE_NAME }}.sha256"

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUNDLE_NAME }}
          path: |
            bundles/${{ env.BUNDLE_NAME }}
            bundles/${{ env.BUNDLE_NAME }}.sha256
          retention-days: 14

      - name: Attach to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bundles/${{ env.BUNDLE_NAME }}
            bundles/${{ env.BUNDLE_NAME }}.sha256
